name: ML Project CI/CD

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  quality-checks:
    name: Linting and Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest black isort
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run linting
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          black --check .
          isort --check-only .

  test:
    name: Run Tests
    needs: quality-checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Check test directory
        run: |
          if [ ! -d "tests" ]; then
            echo "Creating basic test structure..."
            mkdir -p src tests
            echo "def add(a, b): return a + b" > src/math_ops.py
            echo "from src.math_ops import add\n\ndef test_add():\n    assert add(2, 3) == 5" > tests/test_math_ops.py
          fi

      - name: Run tests
        run: |
          python -m pytest tests/ --cov=src/ --cov-report=xml -v

  deploy:
    name: Deploy Model
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Train and Deploy
        run: |
          echo "Starting model training..."
          # Add your model training commands here
          echo "Model training completed"
          echo "Starting deployment..."
          # Add your deployment commands here